### ISSUE TITLE
FaceID add-on fails to start after updating to v0.2.7

### ISSUE THREAD

**Issue by KoenvanH** [SkyTechNerds/faceid#1]
I installed FaceID as a Home Assistant add-on today, and it initially worked without any issues. After updating to version v0.2.7, however, the add-on no longer starts.

The following error appears in the log:

[13:58:58] INFO: Starting FaceID...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/faceid/app/main.py", line 12, in <module>
    from .webui import build_app
  File "/opt/faceid/app/webui.py", line 16, in <module>
    from .engine import FaceEngine, crop_face, find_face_padded
ImportError: cannot import name 'find_face_padded' from 'app.engine' (/opt/faceid/app/engine.py)

**Comment by terryhonn** [comment]
Same error, watching.

**Comment by luckmartin** [comment]
Same error for me

**Comment by NerdyHank** [comment]
Thanks for the quick report — you caught a real one!

**What happened:** a helper function (`find_face_padded`, the padded retry that makes close-up portrait uploads work) existed on my development instance but was missing from the published sources. Fresh installs and updates pulled the broken combination, so the app crashed on import right at startup. My own instance kept running, which is exactly why it slipped through.

**Fixed in [v0.2.8](https://github.com/SkyTechNerds/faceid/releases/tag/v0.2.8)** — update via Settings → Apps → FaceID → Update. If no update shows up yet, reload the app store (or remove and re-add the repository); your face data lives in the app's data volume and is unaffected either way.

To keep this class of bug from ever shipping again, the release script now runs an automated import-consistency check across all modules before anything is published.

Please reopen if v0.2.8 doesn't start cleanly for you.
